# GPS Configuration for robot_localization
frequency: 50
delay: 3.0
magnetic_declination_radians: 0.0  # Set this based on your location
yaw_offset: 0.0
zero_altitude: true
broadcast_utm_transform: true
publish_filtered_gps: true
use_odometry_yaw: true
wait_for_datum: false

# Frame IDs
base_link_frame_id: base_link
map_frame_id: map

# Topic remappings
odom_topic: odometry/filtered
gps_topic: gps/fix
imu_topic: imu

# Datum parameters (set these based on your starting location)
datum: [0.0, 0.0, 0.0]  # [latitude, longitude, yaw] 